sudo: true
language: elixir
elixir:
  - 1.7.1
otp_release:
  - 19.3
matrix:
  include:
    - elixir: 1.7.1
      otp_release: 19.3
after_script:
  - mix inch.report
services:
  - rabbitmq
cache:
  directories:
    - _build
    - deps
